### ISSUE TITLE
Ability to load initial communities as .csv file in addition to .txt file

### ISSUE THREAD

**Issue by cjm23** [LANDIS-II-Foundation/Support-Library-Dlls-v7#14]
Given ease of manipulation of the csv format, could the model take in an initial communities file as a .csv file in place of the .txt file?  Input format would match the output generated by the output community biomass extension and consist of 4 columns: 1) mapcode; 2) species code; 3) age; 4) biomass.

**Comment by rmscheller** [comment]
This change has been implemented in the appropriate library:  https://github.com/LANDIS-II-Foundation/Library-Initial-Community/tree/InputBiomass
